library(vcd)

percaya <- c(pass = 746, av = 0)
percaya_i <- c(pass = 59, av = 258)
percaya_kan <- c(pass = 68, av = 71)
mtx <- rbind(b, d, d2)
rownames(mtx) <- c("percaya", "percaya-i", "percaya-kan")
vcd::assoc(mtx, shade = TRUE)
vcd::assocstats(mtx)
chisq.test(mtx, correct = FALSE)
